CREATE DATABASE IF NOT EXISTS inventory;
USE inventory;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+08:00";

--
-- Database: `inventory`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_barangays`
--

DROP TABLE IF EXISTS `tbl_barangays`;
CREATE TABLE IF NOT EXISTS `tbl_barangays` (
  `brgyname` varchar(50) NOT NULL,
  `city_mun` varchar(50) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_barangays`
--

INSERT INTO `tbl_barangays` (`brgyname`, `city_mun`) VALUES
('Acad', 'Aurora'),
('Alang-alang', 'Aurora'),
('Alegria', 'Aurora'),
('Anonang', 'Aurora'),
('Bagong Mandaue', 'Aurora'),
('Bagong Maslog', 'Aurora'),
('Bagong Oslob', 'Aurora'),
('Bagong Pitogo', 'Aurora'),
('Baki', 'Aurora'),
('Balas', 'Aurora'),
('Balide', 'Aurora'),
('Balintawak', 'Aurora'),
('Bayabas', 'Aurora'),
('Bemposa', 'Aurora'),
('Cabilinan', 'Aurora'),
('Campo Uno', 'Aurora'),
('Ceboneg', 'Aurora'),
('Commonwealth', 'Aurora'),
('Gubaan', 'Aurora'),
('Inasagan', 'Aurora'),
('Inroad', 'Aurora'),
('Kahayagan East', 'Aurora'),
('Kahayagan West', 'Aurora'),
('Kauswagan', 'Aurora'),
('La Paz', 'Aurora'),
('La Victoria', 'Aurora'),
('Lantungan', 'Aurora'),
('Libertad', 'Aurora'),
('Lintugop', 'Aurora'),
('Lubid', 'Aurora'),
('Maguikay', 'Aurora'),
('Mahayahay', 'Aurora'),
('Monte Alegre', 'Aurora'),
('Montela', 'Aurora'),
('Napo', 'Aurora'),
('Panaghiusa', 'Aurora'),
('Poblacion', 'Aurora'),
('Resthouse', 'Aurora'),
('Romarate', 'Aurora'),
('San Jose', 'Aurora'),
('San Juan', 'Aurora'),
('Sapa Loboc', 'Aurora'),
('Tagulalo', 'Aurora'),
('Waterfall', 'Aurora'),
('Baking', 'Bayog'),
('Balukbahan', 'Bayog'),
('Balumbunan', 'Bayog'),
('Bantal', 'Bayog'),
('Bobuan', 'Bayog'),
('Camp Blessing', 'Bayog'),
('Canoayan', 'Bayog'),
('Conacon', 'Bayog'),
('Dagum', 'Bayog'),
('Damit', 'Bayog'),
('Datagan', 'Bayog'),
('Depase', 'Bayog'),
('Depili', 'Bayog'),
('Depore', 'Bayog'),
('Deporehan', 'Bayog'),
('Dimalinao', 'Bayog'),
('Kahayagan', 'Bayog'),
('Kanipaan', 'Bayog'),
('Lamare', 'Bayog'),
('Liba', 'Bayog'),
('Matin-ao', 'Bayog'),
('Matun-og', 'Bayog'),
('Pangi', 'Bayog'),
('Poblacion', 'Bayog'),
('Pulang Bato', 'Bayog'),
('Salawagan', 'Bayog'),
('Sigacad', 'Bayog'),
('Supon', 'Bayog'),
('Bacayawan', 'Dimataling'),
('Baha', 'Dimataling'),
('Balanagan', 'Dimataling'),
('Baluno', 'Dimataling'),
('Binuay', 'Dimataling'),
('Buburay', 'Dimataling'),
('Grap', 'Dimataling'),
('Josefina', 'Dimataling'),
('Kagawasan', 'Dimataling'),
('Lalab', 'Dimataling'),
('Libertad', 'Dimataling'),
('Magahis', 'Dimataling'),
('Mahayag', 'Dimataling'),
('Mercedes', 'Dimataling'),
('Poblacion', 'Dimataling'),
('Saloagan', 'Dimataling'),
('San Roque', 'Dimataling'),
('Sugbay Uno', 'Dimataling'),
('Sumbato', 'Dimataling'),
('Sumpot', 'Dimataling'),
('Tinggabulong', 'Dimataling'),
('Tiniguangan', 'Dimataling'),
('Tipangi', 'Dimataling'),
('Upper Ludiong', 'Dimataling'),
('Bacawan', 'Dinas'),
('Benuatan', 'Dinas'),
('Beray', 'Dinas'),
('Don Jose', 'Dinas'),
('Dongos', 'Dinas'),
('East Migpulao', 'Dinas'),
('Guinicolalay', 'Dinas'),
('Ignacio Garrata', 'Dinas'),
('Kinacap', 'Dinas'),
('Legarda 1', 'Dinas'),
('Legarda 2', 'Dinas'),
('Legarda 3', 'Dinas'),
('Lower Dimaya', 'Dinas'),
('Lucoban', 'Dinas'),
('Ludiong', 'Dinas'),
('Nangka', 'Dinas'),
('Nian', 'Dinas'),
('Old Mirapao', 'Dinas'),
('Pisa-an', 'Dinas'),
('Poblacion', 'Dinas'),
('Proper Dimaya', 'Dinas'),
('Sagacad', 'Dinas'),
('Sambulawan', 'Dinas'),
('San Isidro', 'Dinas'),
('Songayan', 'Dinas'),
('Sumpotan', 'Dinas'),
('Tarakan', 'Dinas'),
('Upper Dimaya', 'Dinas'),
('Upper Sibul', 'Dinas'),
('West Migpulao', 'Dinas'),
('Anonang', 'Dumalinao'),
('Bag-ong Misamis', 'Dumalinao'),
('Bag-ong Silao', 'Dumalinao'),
('Baga', 'Dumalinao'),
('Baloboan', 'Dumalinao'),
('Banta-ao', 'Dumalinao'),
('Bibilik', 'Dumalinao'),
('Calingayan', 'Dumalinao'),
('Camalig', 'Dumalinao'),
('Camanga', 'Dumalinao'),
('Cuatro-cuatro', 'Dumalinao'),
('Locuban', 'Dumalinao'),
('Malasik', 'Dumalinao'),
('Mama', 'Dumalinao'),
('Matab-ang', 'Dumalinao'),
('Mecolong', 'Dumalinao'),
('Metokong', 'Dumalinao'),
('Motosawa', 'Dumalinao'),
('Pag-asa', 'Dumalinao'),
('Paglaum', 'Dumalinao'),
('Pantad', 'Dumalinao'),
('Piniglibano', 'Dumalinao'),
('Rebokon', 'Dumalinao'),
('San Agustin', 'Dumalinao'),
('Sibucao', 'Dumalinao'),
('Sumadat', 'Dumalinao'),
('Tikwas', 'Dumalinao'),
('Tina', 'Dumalinao'),
('Tubo-Pait', 'Dumalinao'),
('Upper Dumalinao', 'Dumalinao'),
('Bag-ong Valencia', 'Dumingag'),
('Bagong Kauswagan', 'Dumingag'),
('Bagong Silang', 'Dumingag'),
('Bucayan', 'Dumingag'),
('Calumanggi', 'Dumingag'),
('Canibongan', 'Dumingag'),
('Caridad', 'Dumingag'),
('Danlugan', 'Dumingag'),
('Dapiwak', 'Dumingag'),
('Datu Totocan', 'Dumingag'),
('Dilud', 'Dumingag'),
('Ditulan', 'Dumingag'),
('Dulian', 'Dumingag'),
('Dulop', 'Dumingag'),
('Guintananan', 'Dumingag'),
('Guitran', 'Dumingag'),
('Gumpingan', 'Dumingag'),
('La Fortuna', 'Dumingag'),
('Labangon', 'Dumingag'),
('Libertad', 'Dumingag'),
('Licabang', 'Dumingag'),
('Lipawan', 'Dumingag'),
('Lower Landing', 'Dumingag'),
('Lower Timonan', 'Dumingag'),
('Macasing', 'Dumingag'),
('Mahayahay', 'Dumingag'),
('Malagalad', 'Dumingag'),
('Manlabay', 'Dumingag'),
('Maralag', 'Dumingag'),
('Marangan', 'Dumingag'),
('New Basak', 'Dumingag'),
('Saad', 'Dumingag'),
('Salvador', 'Dumingag'),
('San Juan', 'Dumingag'),
('San Pablo', 'Dumingag'),
('San Pedro', 'Dumingag'),
('San Vicente', 'Dumingag'),
('Senote', 'Dumingag'),
('Sinonok', 'Dumingag'),
('Sunop', 'Dumingag'),
('Tagun', 'Dumingag'),
('Tamurayan', 'Dumingag'),
('Upper Landing', 'Dumingag'),
('Upper Timonan', 'Dumingag'),
('Bagong Oroquieta', 'Guipos'),
('Baguitan', 'Guipos'),
('Balongating', 'Guipos'),
('Canunan', 'Guipos'),
('Dacsol', 'Guipos'),
('Dagohoy', 'Guipos'),
('Dalapang', 'Guipos'),
('Datagan', 'Guipos'),
('Guling', 'Guipos'),
('Katipunan', 'Guipos'),
('Lintum', 'Guipos'),
('Litan', 'Guipos'),
('Magting', 'Guipos'),
('Poblacion', 'Guipos'),
('Regla', 'Guipos'),
('Sikatuna', 'Guipos'),
('Singclot', 'Guipos'),
('Bogo Calabat', 'Josefina'),
('Dawa', 'Josefina'),
('Ebarle', 'Josefina'),
('Gumahan', 'Josefina'),
('Leonardo', 'Josefina'),
('Litapan', 'Josefina'),
('Lower Bagong Tudela', 'Josefina'),
('Mansanas', 'Josefina'),
('Moradji', 'Josefina'),
('Nemeño', 'Josefina'),
('Nopulan', 'Josefina'),
('Sebukang', 'Josefina'),
('Tagaytay Hill', 'Josefina'),
('Upper Bagong Tudela', 'Josefina'),
('Bogayo', 'Kumalarang'),
('Bolisong', 'Kumalarang'),
('Boyugan East', 'Kumalarang'),
('Boyugan West', 'Kumalarang'),
('Bualan', 'Kumalarang'),
('Diplo', 'Kumalarang'),
('Gawil', 'Kumalarang'),
('Gusom', 'Kumalarang'),
('Kitaan Dagat', 'Kumalarang'),
('Lantawan', 'Kumalarang'),
('Limamawan', 'Kumalarang'),
('Mahayahay', 'Kumalarang'),
('Pangi', 'Kumalarang'),
('Picanan', 'Kumalarang'),
('Poblacion', 'Kumalarang'),
('Salagmanok', 'Kumalarang'),
('Secade', 'Kumalarang'),
('Suminalum', 'Kumalarang'),
('Bagalupa', 'Labangan'),
('Balimbingan', 'Labangan'),
('Binayan', 'Labangan'),
('Bokong', 'Labangan'),
('Bulanit', 'Labangan'),
('Cogonan', 'Labangan'),
('Combo', 'Labangan'),
('Dalapang', 'Labangan'),
('Dimasangca', 'Labangan'),
('Dipaya', 'Labangan'),
('Langapod', 'Labangan'),
('Lantian', 'Labangan'),
('Lower Campo Islam', 'Labangan'),
('Lower Pulacan', 'Labangan'),
('Lower Sang-an', 'Labangan'),
('New Labangan', 'Labangan'),
('Noboran', 'Labangan'),
('Old Labangan', 'Labangan'),
('San Isidro', 'Labangan'),
('Santa Cruz', 'Labangan'),
('Tapodoc', 'Labangan'),
('Tawagan Norte', 'Labangan'),
('Upper Campo Islam', 'Labangan'),
('Upper Pulacan', 'Labangan'),
('Upper Sang-an', 'Labangan'),
('Bagong Kahayag', 'Lakewood'),
('Baking', 'Lakewood'),
('Biswangan', 'Lakewood'),
('Bululawan', 'Lakewood'),
('Dagum', 'Lakewood'),
('Gasa', 'Lakewood'),
('Gatub', 'Lakewood'),
('Lukuan', 'Lakewood'),
('Matalang', 'Lakewood'),
('Poblacion', 'Lakewood'),
('Sapang Pinoles', 'Lakewood'),
('Sebuguey', 'Lakewood'),
('Tiwales', 'Lakewood'),
('Tubod', 'Lakewood'),
('Bulawan', 'Lapuyan'),
('Carpoc', 'Lapuyan'),
('Danganan', 'Lapuyan'),
('Dansal', 'Lapuyan'),
('Dumara', 'Lapuyan'),
('Linokmadalum', 'Lapuyan'),
('Luanan', 'Lapuyan'),
('Lubusan', 'Lapuyan'),
('Mahalingeb', 'Lapuyan'),
('Mandeg', 'Lapuyan'),
('Maralag', 'Lapuyan'),
('Maruing', 'Lapuyan'),
('Molum', 'Lapuyan'),
('Pampang', 'Lapuyan'),
('Pantad', 'Lapuyan'),
('Pingalay', 'Lapuyan'),
('Poblacion', 'Lapuyan'),
('Salambuyan', 'Lapuyan'),
('San Jose', 'Lapuyan'),
('Sayog', 'Lapuyan'),
('Tabon', 'Lapuyan'),
('Talabab', 'Lapuyan'),
('Tiguha', 'Lapuyan'),
('Tininghalang', 'Lapuyan'),
('Tipasan', 'Lapuyan'),
('Tugaya', 'Lapuyan'),
('Bag-ong Balamban', 'Mahayag'),
('Bag-ong Dalaguete', 'Mahayag'),
('Boniao', 'Mahayag'),
('Delusom', 'Mahayag'),
('Diwan', 'Mahayag'),
('Guripan', 'Mahayag'),
('Kaangayan', 'Mahayag'),
('Kabuhi', 'Mahayag'),
('Lourmah', 'Mahayag'),
('Lower Salug Daku', 'Mahayag'),
('Lower Santo Niño', 'Mahayag'),
('Malubo', 'Mahayag'),
('Manguiles', 'Mahayag'),
('Marabanan', 'Mahayag'),
('Panagaan', 'Mahayag'),
('Paraiso', 'Mahayag'),
('Pedagan', 'Mahayag'),
('Poblacion', 'Mahayag'),
('Pugwan', 'Mahayag'),
('San Isidro', 'Mahayag'),
('San Jose', 'Mahayag'),
('San Vicente', 'Mahayag'),
('Santa Cruz', 'Mahayag'),
('Sicpao', 'Mahayag'),
('Tuboran', 'Mahayag'),
('Tulan', 'Mahayag'),
('Tumapic', 'Mahayag'),
('Upper Salug Daku', 'Mahayag'),
('Upper Santo Niño', 'Mahayag'),
('Balintawak', 'Margosatubig'),
('Bularong', 'Margosatubig'),
('Digon', 'Margosatubig'),
('Guinimanan', 'Margosatubig'),
('Igat Island', 'Margosatubig'),
('Josefina', 'Margosatubig'),
('Kalian', 'Margosatubig'),
('Kolot', 'Margosatubig'),
('Limamawan', 'Margosatubig'),
('Limbatong', 'Margosatubig'),
('Lumbog', 'Margosatubig'),
('Magahis', 'Margosatubig'),
('Poblacion', 'Margosatubig'),
('Sagua', 'Margosatubig'),
('Talanusa', 'Margosatubig'),
('Tiguian', 'Margosatubig'),
('Tulapok', 'Margosatubig'),
('Bacahan', 'Midsalip'),
('Balonai', 'Midsalip'),
('Bibilop', 'Midsalip'),
('Buloron', 'Midsalip'),
('Cabaloran', 'Midsalip'),
('Canipay Norte', 'Midsalip'),
('Canipay Sur', 'Midsalip'),
('Cumaron', 'Midsalip'),
('Dakayakan', 'Midsalip'),
('Duelic', 'Midsalip'),
('Dumalinao', 'Midsalip'),
('Ecuan', 'Midsalip'),
('Golictop', 'Midsalip'),
('Guinabot', 'Midsalip'),
('Guitalos', 'Midsalip'),
('Guma', 'Midsalip'),
('Kahayagan', 'Midsalip'),
('Licuro-an', 'Midsalip'),
('Lumpunid', 'Midsalip'),
('Matalang', 'Midsalip'),
('New Katipunan', 'Midsalip'),
('New Unidos', 'Midsalip'),
('Palili', 'Midsalip'),
('Pawan', 'Midsalip'),
('Pili', 'Midsalip'),
('Pisompongan', 'Midsalip'),
('Piwan', 'Midsalip'),
('Poblacion A', 'Midsalip'),
('Poblacion B', 'Midsalip'),
('Sigapod', 'Midsalip'),
('Timbaboy', 'Midsalip'),
('Tulbong', 'Midsalip'),
('Tuluan', 'Midsalip'),
('Alicia', 'Molave'),
('Ariosa', 'Molave'),
('Bagong Argao', 'Molave'),
('Bagong Gutlang', 'Molave'),
('Blancia', 'Molave'),
('Bogo Capalaran', 'Molave'),
('Culo', 'Molave'),
('Dalaon', 'Molave'),
('Dipolo', 'Molave'),
('Dontulan', 'Molave'),
('Gonosan', 'Molave'),
('Lower Dimalinao', 'Molave'),
('Lower Dimorok', 'Molave'),
('Mabuhay', 'Molave'),
('Madasigon', 'Molave'),
('Makuguihon', 'Molave'),
('Maloloy-on', 'Molave'),
('Miligan', 'Molave'),
('Parasan', 'Molave'),
('Rizal', 'Molave'),
('Santo Rosario', 'Molave'),
('Silangit', 'Molave'),
('Simata', 'Molave'),
('Sudlon', 'Molave'),
('Upper Dimorok', 'Molave'),
('Alegria', 'Pagadian'),
('Balangasan', 'Pagadian'),
('Balintawak', 'Pagadian'),
('Baloyboan', 'Pagadian'),
('Banale', 'Pagadian'),
('Bogo', 'Pagadian'),
('Bomba', 'Pagadian'),
('Buenavista', 'Pagadian'),
('Bulatok', 'Pagadian'),
('Bulawan', 'Pagadian'),
('Dampalan', 'Pagadian'),
('Danlugan', 'Pagadian'),
('Dao', 'Pagadian'),
('Datagan', 'Pagadian'),
('Deborok', 'Pagadian'),
('Ditoray', 'Pagadian'),
('Dumagoc', 'Pagadian'),
('Gatas', 'Pagadian'),
('Gubac', 'Pagadian'),
('Gubang', 'Pagadian'),
('Kagawasan', 'Pagadian'),
('Kahayagan', 'Pagadian'),
('Kalasan', 'Pagadian'),
('Kawit', 'Pagadian'),
('La Suerte', 'Pagadian'),
('Lala', 'Pagadian'),
('Lapidian', 'Pagadian'),
('Lenienza', 'Pagadian'),
('Lizon Valley', 'Pagadian'),
('Lourdes', 'Pagadian'),
('Lower Sibatang', 'Pagadian'),
('Lumad', 'Pagadian'),
('Lumbia', 'Pagadian'),
('Macasing', 'Pagadian'),
('Manga', 'Pagadian'),
('Muricay', 'Pagadian'),
('Napolan', 'Pagadian'),
('Palpalan', 'Pagadian'),
('Pedulonan', 'Pagadian'),
('Poloyagan', 'Pagadian'),
('San Francisco', 'Pagadian'),
('San Jose', 'Pagadian'),
('San Pedro', 'Pagadian'),
('Santa Lucia', 'Pagadian'),
('Santa Maria', 'Pagadian'),
('Santiago', 'Pagadian'),
('Santo Niño', 'Pagadian'),
('Tawagan Sur', 'Pagadian'),
('Tiguma', 'Pagadian'),
('Tuburan', 'Pagadian'),
('Tulangan', 'Pagadian'),
('Tulawas', 'Pagadian'),
('Upper Sibatang', 'Pagadian'),
('White Beach', 'Pagadian'),
('Balabawan', 'Pitogo'),
('Balong-balong', 'Pitogo'),
('Colojo', 'Pitogo'),
('Liasan', 'Pitogo'),
('Liguac', 'Pitogo'),
('Limbayan', 'Pitogo'),
('Lower Paniki-an', 'Pitogo'),
('Matin-ao', 'Pitogo'),
('Panubigan', 'Pitogo'),
('Poblacion', 'Pitogo'),
('Punta Flecha', 'Pitogo'),
('San Isidro', 'Pitogo'),
('Sugbay Dos', 'Pitogo'),
('Tongao', 'Pitogo'),
('Upper Paniki-an', 'Pitogo'),
('Bagong Opon', 'Ramon Magsaysay'),
('Bambong Daku', 'Ramon Magsaysay'),
('Bambong Diut', 'Ramon Magsaysay'),
('Bobongan', 'Ramon Magsaysay'),
('Campo IV', 'Ramon Magsaysay'),
('Campo V', 'Ramon Magsaysay'),
('Caniangan', 'Ramon Magsaysay'),
('Dipalusan', 'Ramon Magsaysay'),
('Eastern Bobongan', 'Ramon Magsaysay'),
('Esperanza', 'Ramon Magsaysay'),
('Gapasan', 'Ramon Magsaysay'),
('Katipunan', 'Ramon Magsaysay'),
('Kauswagan', 'Ramon Magsaysay'),
('Lower Sambulawan', 'Ramon Magsaysay'),
('Mabini', 'Ramon Magsaysay'),
('Magsaysay', 'Ramon Magsaysay'),
('Malating', 'Ramon Magsaysay'),
('Paradise', 'Ramon Magsaysay'),
('Pasingkalan', 'Ramon Magsaysay'),
('Poblacion', 'Ramon Magsaysay'),
('San Fernando', 'Ramon Magsaysay'),
('Santo Rosario', 'Ramon Magsaysay'),
('Sapa Anding', 'Ramon Magsaysay'),
('Sinaguing', 'Ramon Magsaysay'),
('Switch', 'Ramon Magsaysay'),
('Upper Laperian', 'Ramon Magsaysay'),
('Wakat', 'Ramon Magsaysay'),
('Betinan', 'San Miguel'),
('Bulawan', 'San Miguel'),
('Calube', 'San Miguel'),
('Concepcion', 'San Miguel'),
('Dao-an', 'San Miguel'),
('Dumalian', 'San Miguel'),
('Fatima', 'San Miguel'),
('Langilan', 'San Miguel'),
('Lantawan', 'San Miguel'),
('Laperian', 'San Miguel'),
('Libuganan', 'San Miguel'),
('Limonan', 'San Miguel'),
('Mati', 'San Miguel'),
('Ocapan', 'San Miguel'),
('Poblacion', 'San Miguel'),
('San Isidro', 'San Miguel'),
('Sayog', 'San Miguel'),
('Tapian', 'San Miguel'),
('Bag-ong Misamis', 'San Pablo'),
('Bubual', 'San Pablo'),
('Buton', 'San Pablo'),
('Culasian', 'San Pablo'),
('Daplayan', 'San Pablo'),
('Kalilangan', 'San Pablo'),
('Kapamanok', 'San Pablo'),
('Kondum', 'San Pablo'),
('Lumbayao', 'San Pablo'),
('Mabuhay', 'San Pablo'),
('Marcos Village', 'San Pablo'),
('Miasin', 'San Pablo'),
('Molansong', 'San Pablo'),
('Pantad', 'San Pablo'),
('Pao', 'San Pablo'),
('Payag', 'San Pablo'),
('Poblacion', 'San Pablo'),
('Pongapong', 'San Pablo'),
('Sacbulan', 'San Pablo'),
('Sagasan', 'San Pablo'),
('San Juan', 'San Pablo'),
('Senior', 'San Pablo'),
('Songgoy', 'San Pablo'),
('Tandubuay', 'San Pablo'),
('Taniapan', 'San Pablo'),
('Ticala Island', 'San Pablo'),
('Tubo-pait', 'San Pablo'),
('Villakapa', 'San Pablo'),
('Bag-ong Baroy', 'Sominot'),
('Bag-ong Oroquieta', 'Sominot'),
('Barubuhan', 'Sominot'),
('Bulanay', 'Sominot'),
('Datagan', 'Sominot'),
('Eastern Poblacion', 'Sominot'),
('Lantawan', 'Sominot'),
('Libertad', 'Sominot'),
('Lumangoy', 'Sominot'),
('New Carmen', 'Sominot'),
('Picturan', 'Sominot'),
('Poblacion', 'Sominot'),
('Rizal', 'Sominot'),
('San Miguel', 'Sominot'),
('Santo Niño', 'Sominot'),
('Sawa', 'Sominot'),
('Tungawan', 'Sominot'),
('Upper Sicpao', 'Sominot'),
('Abong-abong', 'Tabina'),
('Baganian', 'Tabina'),
('Baya-baya', 'Tabina'),
('Capisan', 'Tabina'),
('Concepcion', 'Tabina'),
('Culabay', 'Tabina'),
('Doña Josefina', 'Tabina'),
('Lumbia', 'Tabina'),
('Mabuhay', 'Tabina'),
('Malim', 'Tabina'),
('Manikaan', 'Tabina'),
('New Oroquieta', 'Tabina'),
('Poblacion', 'Tabina'),
('San Francisco', 'Tabina'),
('Tultolan', 'Tabina'),
('Alang-alang', 'Tambulig'),
('Angeles', 'Tambulig'),
('Bag-ong Kauswagan', 'Tambulig'),
('Bag-ong Tabogon', 'Tambulig'),
('Balugo', 'Tambulig'),
('Cabgan', 'Tambulig'),
('Calolot', 'Tambulig'),
('Dimalinao', 'Tambulig'),
('Fabian', 'Tambulig'),
('Gabunon', 'Tambulig'),
('Happy Valley', 'Tambulig'),
('Kapalaran', 'Tambulig'),
('Libato', 'Tambulig'),
('Limamawan', 'Tambulig'),
('Lower Liasan', 'Tambulig'),
('Lower Lodiong', 'Tambulig'),
('Lower Tiparak', 'Tambulig'),
('Lower Usogan', 'Tambulig'),
('Maya-maya', 'Tambulig'),
('New Village', 'Tambulig'),
('Pelocoban', 'Tambulig'),
('Riverside', 'Tambulig'),
('Sagrada Familia', 'Tambulig'),
('San Jose', 'Tambulig'),
('San Vicente', 'Tambulig'),
('Sumalig', 'Tambulig'),
('Tuluan', 'Tambulig'),
('Tungawan', 'Tambulig'),
('Upper Liason', 'Tambulig'),
('Upper Lodiong', 'Tambulig'),
('Upper Tiparak', 'Tambulig'),
('Begong', 'Tigbao'),
('Busol', 'Tigbao'),
('Caluma', 'Tigbao'),
('Diana Countryside', 'Tigbao'),
('Guinlin', 'Tigbao'),
('Lacarayan', 'Tigbao'),
('Lacupayan', 'Tigbao'),
('Libayoy', 'Tigbao'),
('Limas', 'Tigbao'),
('Longmot', 'Tigbao'),
('Maragang', 'Tigbao'),
('Mate', 'Tigbao'),
('Nangan-nangan', 'Tigbao'),
('New Tuburan', 'Tigbao'),
('Nilo', 'Tigbao'),
('Tigbao', 'Tigbao'),
('Timolan', 'Tigbao'),
('Upper Nilo', 'Tigbao'),
('Alindahaw', 'Tukuran'),
('Baclay', 'Tukuran'),
('Balimbingan', 'Tukuran'),
('Buenasuerte', 'Tukuran'),
('Camanga', 'Tukuran'),
('Curvada', 'Tukuran'),
('Laperian', 'Tukuran'),
('Libertad', 'Tukuran'),
('Lower Bayao', 'Tukuran'),
('Luy-a', 'Tukuran'),
('Manilan', 'Tukuran'),
('Manlayag', 'Tukuran'),
('Militar', 'Tukuran'),
('Navalan', 'Tukuran'),
('Panduma Senior', 'Tukuran'),
('Sambulawan', 'Tukuran'),
('San Antonio', 'Tukuran'),
('San Carlos', 'Tukuran'),
('Santo Niño', 'Tukuran'),
('Santo Rosario', 'Tukuran'),
('Sugod', 'Tukuran'),
('Tabuan', 'Tukuran'),
('Tagulo', 'Tukuran'),
('Tinotungan', 'Tukuran'),
('Upper Bayao', 'Tukuran'),
('Ambulon', 'Vincenzo Sagun'),
('Bui-os', 'Vincenzo Sagun'),
('Cogon', 'Vincenzo Sagun'),
('Danan', 'Vincenzo Sagun'),
('Kabatan', 'Vincenzo Sagun'),
('Kapatagan', 'Vincenzo Sagun'),
('Limason', 'Vincenzo Sagun'),
('Linoguayan', 'Vincenzo Sagun'),
('Lumbal', 'Vincenzo Sagun'),
('Lunib', 'Vincenzo Sagun'),
('Maculay', 'Vincenzo Sagun'),
('Maraya', 'Vincenzo Sagun'),
('Sagucan', 'Vincenzo Sagun'),
('Waling-waling', 'Vincenzo Sagun');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_category`
--

DROP TABLE IF EXISTS `tbl_category`;
CREATE TABLE IF NOT EXISTS `tbl_category` (
  `cat_id` int(11) NOT NULL AUTO_INCREMENT,
  `cat_name` varchar(200) NOT NULL,
  PRIMARY KEY (`cat_id`),
  UNIQUE KEY `cat_name` (`cat_name`),
  UNIQUE KEY `cat_name_2` (`cat_name`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_category`
--

INSERT INTO `tbl_category` (`cat_id`, `cat_name`) VALUES
(1, 'Access Point'),
(2, 'Antenna'),
(3, 'Computer'),
(4, 'Electrical'),
(5, 'Hardware'),
(6, 'Networking'),
(7, 'Others & Tools'),
(8, 'Radio Only'),
(9, 'Radio Beams'),
(10, 'Router & Switch');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_invoice`
--

DROP TABLE IF EXISTS `tbl_invoice`;
CREATE TABLE IF NOT EXISTS `tbl_invoice` (
  `invoice_id` int(11) NOT NULL AUTO_INCREMENT,
  `operator_name` varchar(100) NOT NULL,
  `city_mun` varchar(50) NOT NULL,
  `barangay` varchar(50) NOT NULL,
  `grid_coor` varchar(50) NOT NULL,
  `purpose` varchar(50) NOT NULL,
  `requestor` varchar(100) NOT NULL,
  `order_date` date NOT NULL,
  `time_order` varchar(50) NOT NULL,
  `site_type` varchar(50) NOT NULL,
  `twr_height` varchar(50) NOT NULL,
  `powering` varchar(50) NOT NULL,
  `link_ap` varchar(50) NOT NULL,
  `contact_per` varchar(50) NOT NULL,
  `contact_num` varchar(50) NOT NULL,
  PRIMARY KEY (`invoice_id`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_invoice`
--

INSERT INTO `tbl_invoice` (`invoice_id`, `operator_name`, `city_mun`, `barangay`, `grid_coor`, `purpose`, `requestor`, `order_date`, `time_order`, `site_type`, `twr_height`, `powering`, `link_ap`, `contact_per`, `contact_num`) VALUES
(1, 'McJim', 'Pagadian', 'Santo Niño', '7.828, 123.431', 'New Site Installation', 'Team 02', '2021-04-01', '20:52', 'DCS', '20M', 'Hybrid', 'PLDT iGate', 'McJim Castillon Maata', '9776848642'),
(2, 'McJim', 'Pagadian', 'Palpalan', '7.840, 123.382', 'New Site Installation', 'Team 02', '2021-04-05', '00:37', 'MBS', '20M', 'Hybrid', 'Capitol DCS', 'McJim Castillon Maata', '9776848642'),
(3, 'McJim', 'Tukuran', 'Sambulawan', '7.954, 123.461', 'New Site Installation', 'Team 02', '2021-04-09', '01:45', 'MBS', '20M', 'Solar', 'Poloyagan REL', 'McJim Castillon Maata', '9776848642'),
(4, 'McJim', 'San Pablo', 'Kapamanok', '7.676, 123.416', 'New Site Installation', 'Team 02', '2021-05-04', '23:50', 'MBS', '30M', 'Grid', 'Capitol DCS', 'McJim Castillon Maata', '9776848642');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_invoice_detail`
--

DROP TABLE IF EXISTS `tbl_invoice_detail`;
CREATE TABLE IF NOT EXISTS `tbl_invoice_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_code` char(7) NOT NULL,
  `product_name` varchar(100) NOT NULL,
  `qty` int(11) NOT NULL,
  `product_unit` varchar(50) NOT NULL,
  `serial_mac` varchar(50) NOT NULL,
  `order_date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=63 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_invoice_detail`
--

INSERT INTO `tbl_invoice_detail` (`id`, `invoice_id`, `product_id`, `product_code`, `product_name`, `qty`, `product_unit`, `serial_mac`, `order_date`) VALUES
(18, 1, 51, 'ERI-10G', 'Edge Router Infinity', 1, 'Set', 'F492BF85AD0E', '2021-04-01'),
(19, 1, 50, 'MIK-CCR', 'Mikrotik CCR 12G', 1, 'Set', 'C4AD34E273C8', '2021-04-01'),
(20, 1, 52, 'ESW-16X', 'Edge Switch 16 XG', 6, 'Set', '74ACB9AC2D48', '2021-04-01'),
(21, 1, 4, 'AF5-HBB', 'Air Fiber 5Ghz', 2, 'Set', '24A43C38EC86', '2021-04-01'),
(22, 1, 4, 'LBE-5AC', 'Lite Beam Gen2', 3, 'Set', '602232D80EB4', '2021-04-01'),
(23, 1, 7, 'RPG-RG2', 'Rocket Prism Gen2', 5, 'Set', 'E063DADED9CB', '2021-04-01'),
(24, 1, 9, 'USW-8PT', 'Unifi Switch 8Port', 2, 'Set', '74ACB9EA87B9', '2021-04-01'),
(25, 1, 1, 'UAP-ACM', 'Unifi AC Mesh', 10, 'Set', 'F492BFC98897', '2021-04-01'),
(26, 1, 42, 'NET-RAC', 'Network Cabinet', 2, 'Assy', 'N/A', '2021-04-01'),
(34, 2, 52, 'ESW-16X', 'Edge Switch 16 XG', 1, 'Set', '74:AC:B9:AC:2D:93', '2021-04-05'),
(29, 1, 53, 'SFP-10G', 'RRJ45 SFP Module', 15, 'Piece', 'N/A', '2021-04-01'),
(30, 1, 5, 'AMS-45D', 'Rocket Sector Antenna', 4, 'Set', 'N/A', '2021-04-01'),
(31, 1, 6, 'RD5-34D', 'Rocket Dish Antenna', 1, 'Set', 'N/A', '2021-04-01'),
(32, 1, 10, 'AMO-513', 'Rocket Omni Antenna', 1, 'Set', 'N/A', '2021-04-01'),
(33, 1, 15, 'SOL-200', 'Solar Panel 200W', 12, 'Piece', 'N/A', '2021-04-01'),
(35, 2, 4, 'AF5-HBB', 'Air Fiber 5Ghz', 1, 'Set', '24:A4:3C:38:EC:6A', '2021-04-05'),
(36, 2, 59, 'PBE-620', ' Power Beam AC 620', 1, 'Set', 'F4:92:BF:BE:11:3A', '2021-04-05'),
(37, 2, 7, 'RPG-RG2', 'Rocket Prism Gen2', 12, 'Set', '24:5A:4C:08:B8:62', '2021-04-05'),
(38, 2, 3, 'LBE-5AC', 'Lite Beam Gen2', 1, 'Set', '68:D7:9A:94:D6:FA', '2021-04-05'),
(39, 2, 15, 'SOL-200', 'Solar Panel 200W', 12, 'Piece', 'N/A', '2021-04-05'),
(40, 2, 14, 'BAT-40A', 'Gel Battery 40AH', 12, 'Piece', 'N/A', '2021-04-05'),
(41, 2, 53, 'SFP-10G', 'RJ45 SFP Module ', 10, 'Piece', 'N/A', '2021-04-05'),
(42, 2, 33, 'GIP-2IN', 'GI Pipe 2 Inches', 5, 'Lenght', 'N/A', '2021-04-05'),
(43, 2, 34, 'SVL-CLM', 'Swivel Pipe Clamp', 20, 'Piece', 'N/A', '2021-04-05'),
(44, 3, 52, 'ESW-16X', 'Edge Switch 16 XG', 1, 'Set', '74:AC:B9:AC:29:0A', '2021-04-09'),
(45, 3, 4, 'AF5-HBB', 'Air Fiber 5Ghz', 3, 'Set', '24:A4:3C:38:EC:88', '2021-04-09'),
(46, 3, 7, 'RPG-RG2', 'Rocket Prism Gen2', 10, 'Set', '24:5A:4C:08:BD:1A', '2021-04-09'),
(47, 3, 15, 'SOL-200', 'Solar Panel 200W', 12, 'Piece', 'N/A', '2021-04-09'),
(48, 3, 13, 'BAT-100', 'Gel Battery 100AH', 4, 'Piece', 'N/A', '2021-04-09'),
(49, 3, 14, 'BAT-40A', 'Gel Battery 40AH', 8, 'Piece', 'N/A', '2021-04-09'),
(50, 3, 33, 'GIP-2IN', 'GI Pipe 2 Inches', 4, 'Lenght', 'N/A', '2021-04-09'),
(51, 3, 34, 'SVL-CLM', 'Swivel Pipe Clamp', 20, 'Piece', 'N/A', '2021-04-09'),
(52, 3, 42, 'NET-RAC', 'Network Cabinet', 4, 'Assy', 'N/A', '2021-04-09'),
(53, 2, 42, 'NET-RAC', 'Network Cabinet', 3, 'Assy', 'N/A', '2021-04-05'),
(54, 4, 4, 'AF5-HBB', 'Air Fiber 5Ghz', 1, 'Set', '24:A4:3C:38:EC:85', '2021-05-04'),
(55, 4, 60, 'MRB-AH4', 'Mikrotik RB1100 AH4X', 1, 'Set', 'C4:AD:34:E2:73:C8', '2021-05-04'),
(56, 4, 7, 'RPG-RG2', 'Rocket Prism Gen2', 7, 'Set', '24:5A:4C:08:B9:B4', '2021-05-04'),
(57, 4, 3, 'LBE-5AC', 'Lite Beam Gen2', 1, 'Set', '68:D7:9A:94:D2:8B', '2021-05-04'),
(58, 4, 3, 'LBE-5AC', 'Lite Beam Gen2', 1, 'Set', '68:D7:9A:94:E0:70', '2021-05-04'),
(59, 4, 42, 'NET-RAC', 'Network Cabinet', 2, 'Assy', 'N/A', '2021-05-04'),
(60, 4, 53, 'SFP-10G', 'RJ45 SFP Module ', 5, 'Piece', 'N/A', '2021-05-04'),
(61, 4, 33, 'GIP-2IN', 'GI Pipe 2 Inches', 5, 'Lenght', 'N/A', '2021-05-04'),
(62, 4, 34, 'SVL-CLM', 'Swivel Pipe Clamp', 20, 'Piece', 'N/A', '2021-05-04');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_product`
--

DROP TABLE IF EXISTS `tbl_product`;
CREATE TABLE IF NOT EXISTS `tbl_product` (
  `product_id` int(11) NOT NULL AUTO_INCREMENT,
  `product_code` char(7) NOT NULL,
  `product_name` varchar(200) NOT NULL,
  `product_category` varchar(200) NOT NULL,
  `stock` int(11) NOT NULL,
  `min_stock` int(11) NOT NULL,
  `product_unit` varchar(200) NOT NULL,
  `description` varchar(200) NOT NULL,
  `img` varchar(200) NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE KEY `product_code` (`product_code`,`product_name`)
) ENGINE=MyISAM AUTO_INCREMENT=61 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_product`
--

INSERT INTO `tbl_product` (`product_id`, `product_code`, `product_name`, `product_category`, `stock`, `min_stock`, `product_unit`, `description`, `img`) VALUES
(1, 'UAP-ACM', 'Unifi AC Mesh', 'Access Point', 990, 100, 'Set', 'Ubiquity Unify Access Point 5Ghz / 2.4Ghz AC Mesh', 'UAP-ACM.jpg'),
(2, 'PBE-5AC', 'Power Beam AC 400', 'Radio Beams', 100, 5, 'Set', 'Ubiquiti Power Beam 5AC 400mm ', 'PBE-5AC.jpg'),
(3, 'LBE-5AC', 'Lite Beam Gen2', 'Radio Beams', 595, 5, 'Set', 'Ubiquiti Light Beam 5AC Gen 2', 'LBE-5AC.jpg'),
(4, 'AF5-HBB', 'Air Fiber 5Ghz', 'Radio Beams', 11, 2, 'Set', 'Ubiquiti Air Fiber 5Ghz 100Km Bridge', 'AF5-HBB.jpg'),
(5, 'AMS-45D', 'Rocket Sector Antenna', 'Antenna', 46, 2, 'Set', 'Ubiquiti Rocket Sector Antenna 5AC 22dbm 45Deg', 'AMS-45D.jpg'),
(6, 'RD5-34D', 'Rocket Dish Antenna', 'Antenna', 49, 2, 'Set', 'Ubiquiti Rocket Dish Antenna 5AC 34dbm', 'RD5-34D.jpg'),
(7, 'RPG-RG2', 'Rocket Prism Gen2', 'Radio Only', 70, 5, 'Set', 'Ubiquiti Rocket Prism Gen2 Base Station Radio', 'RPG-RG2.jpg'),
(8, 'UNS-4PT', 'Nano Switch Surge', 'Networking', 600, 10, 'Set', 'Ubiquiti Nano Switch 4Port Outdoor', 'UNS-4PT.jpg'),
(9, 'USW-8PT', 'Unifi Switch 8Port', 'Router & Switch', 28, 2, 'Set', 'Ubiquiti 8 Port Unifi Managed Switch', 'USW-8PT.jpg'),
(10, 'AMO-513', 'Omni Antenna 2.4', 'Antenna', 199, 5, 'Set', 'Ubiquiti 13dbm 2.4 Ghz Omni Antenna', 'AMO-513.jpg'),
(11, 'TPL-SW4', 'TP-Link 4P Switch', 'Router & Switch', 200, 10, 'Set', 'TP-Link Switch/Hub 4 Port ', 'TPL-SW4.jpg'),
(12, 'BAT-150', 'Gel Battery 150AH', 'Electrical', 19, 2, 'Piece', 'Gel Battery 150AH 12V No Product Name', 'BAT-150.jpg'),
(13, 'BAT-100', 'Gel Battery 100AH', 'Electrical', 16, 2, 'Piece', 'Gel Battery 100AH 12V Blue Sun', 'BAT-100.jpg'),
(14, 'BAT-40A', 'Gel Battery 40AH', 'Electrical', 30, 2, 'Piece', 'Gel Battery 40AH 12V Rosen Solar', 'BAT-40A.jpg'),
(15, 'SOL-200', 'Solar Panel 200W', 'Electrical', 26, 2, 'Piece', 'Solar Panel 200W 18V', 'SOL-200.jpg'),
(16, 'SOL-300', 'Solar Panel 300W', 'Electrical', 299, 5, 'Piece', 'Solar Panel 300W 30V', 'SOL-300.jpg'),
(17, 'SOL-CTR', 'Solar Controller', 'Electrical', 50, 2, 'Piece', 'Solar Charge Controller 10 Ampheres', 'SOL-CTR.jpg'),
(18, 'HDR-BAT', 'Hand Drill (Cordless)', 'Electrical', 5, 1, 'Set', 'Hand Drill Battery Drive Dewalt', 'HDR-BAT.jpg'),
(19, 'HDR-WRD', 'Hand Drill  (Wired)', 'Electrical', 5, 1, 'Set', 'Handrill Wired Makita', 'HDR-WRD.jpg'),
(49, 'PWR-KAL', 'Power Kalan', 'Others & Tools', 1, 1, 'Set', 'Power Kalan', 'SUP-KAL.jpg'),
(20, 'GRD-CRG', 'Grinder (Cordless)', 'Electrical', 5, 1, 'Set', 'Cordless Grinder Makita', 'GRD-CRG.jpg'),
(21, 'DEV-ENC', 'Device Enclosure', 'Electrical', 30, 5, 'Piece', 'Device Enclosure Outdoor', 'DEV-ENC.jpg'),
(22, 'SDW-DPL', 'Service Drop Wire', 'Electrical', 200, 10, 'Meter', 'Duplex Service Drop Wire', 'SDW-DPL.jpg'),
(23, 'THN-2MM', 'THHN Wire 2.0 mm', 'Electrical', 20, 2, 'Box', 'THHN Wire 2mm', 'THN-2MM.jpg'),
(24, 'THN-3MM', 'THHN Wire 3.5 mm', 'Electrical', 20, 2, 'Box', 'THHN Wire 3.5 mm', 'THN-3MM.jpg'),
(25, 'THN-5MM', 'THHN Wire 5.5 mm', 'Electrical', 20, 2, 'Box', 'THHN Wire 5.5 mm', 'THN-5MM.jpg'),
(26, 'FLT-C10', 'Flat Cord 10 mm', 'Electrical', 100, 5, 'Meter', 'Flat Cord Electrical Wire', 'FLT-C10.jpg'),
(27, 'CBS-6AH', 'Circuit  Breaker 6A', 'Electrical', 100, 10, 'Piece', 'Circuit Breaker 6 Ampheres', 'CBS-6AH.jpg'),
(28, 'CBS-10A', 'Circuit Breaker 10A', 'Electrical', 100, 10, 'Piece', 'Circuit Breaker 10 Ampheres', 'CBS-10A.jpg'),
(29, 'DIN-RLL', 'Breaker DIN Rail ', 'Electrical', 100, 10, 'Piece', 'Circuit Breaker Switch DIN Rail', 'DIN-RLL.jpg'),
(30, 'PVC-P3P', 'PVC Pipe 3/4 ', 'Electrical', 100, 10, 'Lenght', 'PVC Pipe 3/4\" 10\'', 'PVC-P3P.jpg'),
(31, 'PSW-INV', 'Charger Inverter', 'Electrical', 49, 2, 'Set', 'AC Pure Sine Wave Charger Inverter 3Kw', 'PSW-INV.jpg'),
(32, 'FLD-LGT', 'Flood Light', 'Electrical', 5, 1, 'Piece', 'Flood Light 100 Watts', 'FLD-LGT.jpg'),
(33, 'GIP-2IN', 'GI Pipe 2 Inches', 'Hardware', 986, 20, 'Lenght', 'Galvanized Iron Pipe  2 Inches Schedule 40', 'GIP-2IN.jpg'),
(34, 'SVL-CLM', 'Swivel Pipe Clamp', 'Hardware', 940, 10, 'Piece', 'Swivel Pipe Clamp 2 Inches', 'SVL-CLM.jpg'),
(35, 'TLS-ADJ', 'Adjustable Wrench', 'Others & Tools', 20, 2, 'Piece', 'Adjustable Wrench No. 10', 'TLS-ADJ.jpg'),
(36, 'TLS-UNW', 'Universal Wrench', 'Others & Tools', 20, 2, 'Piece', 'Universal Wrench', 'TLS-UNW.jpg'),
(37, 'BAN-T10', 'Tie Wire (Banting)', 'Hardware', 100, 10, 'Roll', 'Galvanized Tie Wire (Banting) #10', 'BAN-T10.jpg'),
(38, 'HRD-ANB', 'GI Angle Bar', 'Hardware', 200, 10, 'Lenght', 'Galvanized Iron Angle Bar 1/14\" 2\"', 'HRD-ANB.jpg'),
(39, 'HRD-TRN', 'Turn Buckle', 'Hardware', 200, 10, 'Piece', 'Galvanized Iron Turn Buckle #12', 'HRD-TRN.jpg'),
(40, 'LAD-EXT', 'Ladder Extended', 'Others & Tools', 4, 1, 'Piece', 'Extended Ladder 24 Feet', 'LAD-EXT.jpg'),
(41, 'LAD-FLD', 'Ladder Folding', 'Others & Tools', 4, 1, 'Piece', 'Folding Ladder 12 Feet', 'LAD-FLD.jpg'),
(42, 'NET-RAC', 'Network Cabinet', 'Networking', 44, 2, 'Assy', 'Harwell Outdoor Network Rack Cabinet', 'NET-RAC.jpg'),
(43, 'NCB-STP', 'Cable Cat6  STP', 'Networking', 100, 10, 'Box', 'STP Cat6 Cable Outdoor', 'NCB-STP.jpg'),
(44, 'NCB-UTP', 'Cable Cat6 UTP ', 'Networking', 100, 10, 'Box', 'UTP Cat 6 Cable Indoor', 'NCB-UTP.jpg'),
(45, 'SAF-HAR', 'Safety Harness', 'Others & Tools', 20, 2, 'Set', 'Safety Harness', 'SAF-HAR.jpg'),
(46, 'SAF-HAT', 'Hard Hat', 'Others & Tools', 20, 2, 'Piece', 'Safety Hard Hat', 'SAF-HAT.jpg'),
(47, 'BIN-LRG', 'Binoculars', 'Others & Tools', 10, 1, 'Piece', 'Long Ranged Binoculars', 'BIN-LRG.jpg'),
(50, 'MIK-CCR', 'Mikrotik Core Router', 'Router & Switch', 1, 1, 'Set', 'MikroTik Cloud Core Router CCR1036-12G4S-EM', 'MIK-CCR.jpg'),
(51, 'ERI-10G', 'Edge Router Infinity', 'Router & Switch', 1, 1, 'Set', 'Ubiquiti Edge Router Infinity 16-Core, 1.8 GHz Processor ', 'ERI-10G.jpg'),
(52, 'ESW-16X', 'Edge Switch 16 XG', 'Router & Switch', 5, 1, 'Set', 'Ubiquiti Edge Switch 16 XG, 320 Gbps', 'ESW-16X.jpg'),
(53, 'SFP-10G', 'RJ45 SFP Module ', 'Networking', 0, 2, 'Piece', 'UF-RJ45-10G Ethernet to SFP Ports Module ', 'SFP-10G.jpg'),
(54, 'UPC-R45', 'Ethernet Patch Cable ', 'Networking', 100, 5, 'Piece', 'UniFi Ethernet Patch Cable UC Patch-RJ45-BL', 'UPC-R45.jpg'),
(55, 'TCC-R45', 'RJ45 Cable Connector', 'Networking', 30, 5, 'Pack', 'Network TOUGHCable Connectors (Pack of 100) ', 'TCC-R45.jpg'),
(56, 'DPC-CI7', 'Core i7 Desktop', 'Computer', 1, 1, 'Set', 'Intel Core i7 Desktop Computer', 'DPC-CI7.jpg'),
(57, 'LPC-CI7', 'Laptop Computer', 'Computer', 6, 1, 'Set', 'Intel Core i7 ROG Strix Laptop Computer', 'LPC-CI7.jpg'),
(58, 'UCT-NET', 'Crimping Tools', 'Networking', 20, 2, 'Set', 'Universal Network Cable Crimping Tools', 'UCT-NET.jpg'),
(59, 'PBE-620', ' Power Beam AC 620', 'Radio Beams', 599, 5, 'Set', 'Ubiquiti PowerBeam AC 620 mm Dish Reflector', 'PBE-620.jpg'),
(60, 'MRB-AH4', 'Mikrotik RB1100 AH4X', 'Router & Switch', 4, 1, 'Set', 'MikroTik RB1100AHx4 Dude Edition Router', 'MRB-AH4.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_unit`
--

DROP TABLE IF EXISTS `tbl_unit`;
CREATE TABLE IF NOT EXISTS `tbl_unit` (
  `kd_unit` int(2) NOT NULL AUTO_INCREMENT,
  `nm_unit` varchar(20) NOT NULL,
  PRIMARY KEY (`kd_unit`),
  UNIQUE KEY `nm_unit` (`nm_unit`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_unit`
--

INSERT INTO `tbl_unit` (`kd_unit`, `nm_unit`) VALUES
(1, 'Klgs'),
(2, 'Roll'),
(3, 'Sheet'),
(4, 'Set'),
(5, 'Assy'),
(6, 'Box'),
(7, 'Pack'),
(8, 'Piece'),
(9, 'Lenght'),
(10, 'Meter');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_user`
--

DROP TABLE IF EXISTS `tbl_user`;
CREATE TABLE IF NOT EXISTS `tbl_user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(200) NOT NULL,
  `fullname` varchar(200) NOT NULL,
  `password` varchar(200) NOT NULL,
  `role` varchar(15) NOT NULL,
  `is_active` tinyint(4) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_user`
--

INSERT INTO `tbl_user` (`user_id`, `username`, `fullname`, `password`, `role`, `is_active`) VALUES
(1, 'McJim', 'McJim Maata', 'McJim654123', 'Admin', 1),
(12, 'Justin', 'Justin Paolo Herrera', '1234', 'Admin', 1),
(5, 'Mark', 'John Mark Decierdo', '1234', 'Operator', 1),
(6, 'Ariel', 'Ariel Lance Labador', '1234', 'Operator', 1),
(7, 'Axle', 'Axle Van Lorico', '1234', 'Operator', 1),
(9, 'Decon', 'Decon Genova', '1234', 'Operator', 1),
(10, 'Junrey', 'Junrey Saman', '1234', 'Operator', 1),
(11, 'Jeff', 'Jefferson Rosal', '1234', 'Operator', 1),
(14, 'Rudy', 'Rudy Batoctoy', '1234', 'Admin', 1);
